### ISSUE TITLE
Installing Jenkins on Docker

### ISSUE THREAD

**Issue by amitchettri** [cirulls/hands-on-jenkins#32]
Hello Sandro, 

I followed your provided steps to install jenkins on docker. But when i access localhost:8080 and after I add the temporary admin password I get the message **"This Jenkins instance appears to be offline."** checking over google i get to know that my docker contain is not having the internet access (may be)

Can you help me resolve it? 

**lab setup:**
1. I am using win10
2. Create a VM with centos in VMware workstation
3. Installed docker on it
4. Pull and run the jenkins/jenkins:lts

![image](https://user-images.githubusercontent.com/46727623/73834711-3734e700-4832-11ea-8431-2bea9a6c357f.png)

**Comment by Azher-Khaleel** [comment]
Hi ,
I had the same issue on iMac and resolved by replacing https with http in this file Jenkins.model.JenkinsLocationConfiguration.xml and restart Jenkins.

Line in the above should be: <jenkinsUrl>http://localhost:8080/jenkins/</jenkinsUrl>
